#!/bin/sh

clear

SALIR=0
OPCION=0
while [ $SALIR -eq 0 ]; do
echo -e "\e[1;40;32m####################################################################\e[0m"
echo -e "\e[1;40;32m#								   #\e[0m"
echo -e "\e[1;40;32m# SCRIPT PUBLICADO POR perraka DE MULTICS.ES Y MODIFICADO POR PIFO #\e[0m"
echo -e "\e[1;40;32m# FOROS AUTORIZADOS PARA PUBLICACION                               #\e[0m"
echo -e "\e[1;40;32m# MULTICSFORO.COM                                                  #\e[0m"
echo -e "\e[1;40;32m# MULTICS.EU                                                       #\e[0m"
echo -e "\e[1;40;32m# MULTICS.ES                                                       #\e[0m"
echo -e "\e[1;40;32m#								   #\e[0m"
echo -e "\e[1;40;32m#			ULTIMA EDICION 27-05-2021		   #\e[0m"
echo -e "\e[1;40;32m#								   #\e[0m"
echo -e "\e[1;40;32m####################################################################\e[0m"
echo -e "\e[38;5;75mMenu:\e[0m"

   echo -e "\e[1;40;37m1) \e[1;40;32mInstalar Firewall\e[0m"
   echo -e "\e[1;40;37m2) \e[1;40;31mEliminar Firewall\e[0m"
   echo -e "\e[1;40;37m3) \e[38;5;75mManual de Uso Para Ban/Unban\e[0m"
   echo -e "\e[1;40;376m4) \e[38;5;226mSalir\e[0m"
   echo -e "\e[38;5;75mOpcion seleccionada:\e[0m"
   read OPCION
   case $OPCION in
       1)
clear
apt-get install dnsutils curl -y > /dev/null 2>&1
mkdir /etc/myOwnFirewall > /dev/null 2>&1
wget https://pifo-emu.github.io/Firewall-multics/Firewall -O /etc/myOwnFirewall/myOwnFirewall > /dev/null 2>&1
chmod +x -R /etc/myOwnFirewall

#CACHE
Cax1=$(netstat -plnu | grep 0.0.0.0: | grep -v 123 |  cut -f2 -d ':' | cut -f1 -d ' ')
Cax0=$(echo $Cax1 | sed "s/\s/,/g")

#SSH
SSH1=$(netstat -putona | grep sshd | grep 0.0.0.0: |  cut -f2 -d ':' | cut -f1 -d ' ')

#RESTO DE PUERTOS
P0rt=$(netstat -plnt | grep 0.0.0.0: | grep -v $SSH1 |  cut -f2 -d ':' | cut -f1 -d ' ')
P1rt=$(echo $P0rt | sed "s/\s/,/g")

#RED
red1=$(ip a | grep $(curl -s -4 ifconfig.me) | cut -f11-12 -d ' ')


#RED
echo "SE A DETECTADO $red1 COMO NOMBRE DE TARJETA DE RED"
echo -e "\e[1;40;35m$red1 ES EL NOMBRE CORRECTO DE TU TARJETA DE RED?\e[0m" 

   echo -e "\e[1;40;37m1) \e[1;40;32mSI\e[0m"
   echo -e "\e[1;40;37m2) \e[1;40;31mNO\e[0m"

read red0
   case $red0 in
       1) echo OK
sed s/"red_"/"$red1"/g -i /etc/myOwnFirewall/myOwnFirewall 

           ;;

       2) echo -e "\e[1;40;35mDIME EL NOMBRE DE TU TARJETA DE RED\e[0m" 
read red_
sed s/"red_"/"$red_"/g -i /etc/myOwnFirewall/myOwnFirewall 

           ;;
       *)
           clear
         echo "Opcion erronea";;
esac





#PORT MULTICS
echo "ESTOS SON LOS PUERTOS USADOS POR LA MULTICS, MENOS EL DE CACHE.?"
echo -e "\e[1;40;35m$P1rt\e[0m" 

   echo -e "\e[1;40;37m1) \e[1;40;32mSI\e[0m"
   echo -e "\e[1;40;37m2) \e[1;40;31mNO\e[0m"

read P0rt_
   case $P0rt_ in
       1) echo OK
	    sed s/"pro_"/"$P1rt"/g -i /etc/myOwnFirewall/myOwnFirewall 

           ;;

       2) echo -e "\e[1;40;35mDIME TUS PUERTOS QUE USA LA MULTICS\e[0m"
           echo -e "\e[1;40;35mPARA CCCAM, MGCAMD, NEWCAMD O CUALQUIER OTRO PROTOCOLO QUE USES, QUE NO SEA EL DE CACHE.\e[0m"
           echo -e "\e[1;40;35mE.j: 4000,12001,18003,8000:8010\e[0m"
	    read pro_
	    sed s/"pro_"/"$pro_"/g -i /etc/myOwnFirewall/myOwnFirewall 
           ;;
	*)
           clear
         echo "Opcion erronea";;

esac


#PORT MULTICS CACHE
echo "ESTOS SON LOS PUERTOS USADOS POR LA CACHE DE LA MULTICS.?"
echo -e "\e[1;40;35m$Cax0\e[0m" 

   echo -e "\e[1;40;37m1) \e[1;40;32mSI\e[0m"
   echo -e "\e[1;40;37m2) \e[1;40;31mNO\e[0m"

read Cax0_
   case $Cax0_ in
       1) echo OK
	    sed s/"cac_"/"$Cax0"/g -i /etc/myOwnFirewall/myOwnFirewall 

           ;;

       2) echo -e "\e[1;40;35mDIME LOS PUERTOS USADOS POR LA CACHE DE LA MULTICS\e[0m"
           echo -e "\e[1;40;35mE.j: 4000,12001,18003,8000:8010\e[0m"
	    read cac_
	    sed s/"cac_"/"$cac_"/g -i /etc/myOwnFirewall/myOwnFirewall 
           ;;
	*)
           clear
         echo "Opcion erronea";;

esac

#PORT SSH

echo "ESTE ES TU PUERTO USADO PARA SSH.?"
echo -e "\e[1;40;35m$SSH1\e[0m" 

   echo -e "\e[1;40;37m1) \e[1;40;32mSI\e[0m"
   echo -e "\e[1;40;37m2) \e[1;40;31mNO\e[0m"

read SSH3
   case $SSH3 in
       1) echo OK
sed s/"ss_"/"$SSH1"/g -i /etc/myOwnFirewall/myOwnFirewall 

           ;;

       2) echo -e "\e[1;40;35mDIME TU PUERTO SSH\e[0m"
echo -e "\e[1;40;31m!!ATENCION!! NO TE EQUIVOQUES\e[0m"
read ss_
sed s/"ss_"/"$ss_"/g -i /etc/myOwnFirewall/myOwnFirewall 

           ;;
       *)
           clear
         echo "Opcion erronea";;
esac

#PORT TCP

echo "NESECITAS ABRIT OTRO PUERTO TCP.?"

   echo -e "\e[1;40;37m1) \e[1;40;32mSI\e[0m"
   echo -e "\e[1;40;37m2) \e[1;40;31mNO\e[0m"

read TCP3
   case $TCP3 in
       1) echo OK
echo -e "\e[1;40;35mDIME EL/LOS PUERTO TCP SEPARADOS POR ',' COMAS\e[0m"
read web_
sed s/"web_"/"$web_"/g -i /etc/myOwnFirewall/myOwnFirewall
sed -i "199i\$IPT -A INPUT  -i \$ETH  -p tcp --match multiport --dports \$TCP -j ACCEPT" /etc/myOwnFirewall/myOwnFirewall

           ;;

       2) echo OK

           ;;
       *)
           clear
         echo "Opcion erronea";;
esac

#PORT UDP

echo "NESECITAS ABRIT OTRO PUERTO UPD.?"

   echo -e "\e[1;40;37m1) \e[1;40;32mSI\e[0m"
   echo -e "\e[1;40;37m2) \e[1;40;31mNO\e[0m"

read UDP3
   case $UDP3 in
       1) echo OK
echo -e "\e[1;40;35mDIME EL/LOS PUERTO TCP SEPARADOS POR ',' COMAS\e[0m"
read pr2_
sed s/"pr2_"/"$pr2_"/g -i /etc/myOwnFirewall/myOwnFirewall
sed -i "200i\$IPT -A INPUT -i \$ETH -p udp -m udp --match multiport --dports \$UDP -j ACCEPT" /etc/myOwnFirewall/myOwnFirewall

           ;;

       2) echo OK

           ;;
       *)
           clear
         echo "Opcion erronea";;
esac



#TEST FIREWALL
clear
echo -e "\e[1;40;31m!!ATENCION!! AHORA REALIZAREMOS UN TEST TENDRAS 1 MINUTO\e[0m"
echo -e "\e[1;40;31mPRUEBA QUE TENGAS ACCESO A LA MULTICS Y A SSH\e[0m"

ln -s /etc/myOwnFirewall/myOwnFirewall /usr/sbin/f > /dev/null 2>&1
ln -s /etc/myOwnFirewall/myOwnFirewall  /etc/init.d/myOwnFirewall > /dev/null 2>&1
touch /etc/myOwnFirewall/banList > /dev/null 2>&1

/etc/myOwnFirewall/myOwnFirewall test

echo -e "\e[1;40;31m!!ATENCION!! TUVISTES ACCESO A SSH Y A LA MULTICS?\e[0m"

   echo -e "\e[1;40;37m1) \e[1;40;32mSI\e[0m"
   echo -e "\e[1;40;37m2) \e[1;40;31mNO\e[0m"

read T3ST
   case $T3ST in
       1) 
           echo "OK ACTIVAMOS EL FIREWALL"
           systemctl enable myOwnFirewall > /dev/null 2>&1
           /etc/myOwnFirewall/myOwnFirewall start
           ;;

       2) 
           echo "VUELVE A INTENTARLO EN OTRO MOMENTO HOY NO ES TU DIA"
           echo "O SOLICITA AYUDA EN EL FORO"
           echo "AHORA ELIMINARE LO QUE YA SE HABIA INSTALADO PARA QUE EMPIECES NUEVAMENTE"
           rm -rf  /etc/myOwnFirewall /usr/sbin/f /etc/init.d/myOwnFirewall > /dev/null 2>&1
           ;;
       *)
           clear
         echo "Opcion erronea";;

esac
clear
         echo -e "\e[1;40;31mFirewall Instalado\e[0m"

          ;;


#TERMINAMOS INSTALACION

       2)
         clear
         /etc/myOwnFirewall/myOwnFirewall stop  > /dev/null 2>&1
         rm -rf  /etc/myOwnFirewall /usr/sbin/f /etc/init.d/myOwnFirewall > /dev/null 2>&1
         rm /tmp/install > /dev/null 2>&1
         echo -e "\e[1;40;31mFirewall Eliminado\e[0m"
         ;;

       3)
         clear
         echo -e "\e[1;40;32mBan IP: /etc/myOwnFirewall/myOwnFirewall ban \e[38;5;226m[IP]\e[0m"
         echo -e "\e[1;40;32mBan IP: /etc/myOwnFirewall/myOwnFirewall ban \e[38;5;226m[HOST]\e[0m"
         echo -e "\e[1;40;32mUnban IP: /etc/myOwnFirewall/myOwnFirewall unban \e[38;5;226m[IP]\e[0m"
         echo -e "\e[1;40;32mUnban IP: /etc/myOwnFirewall/myOwnFirewall unban \e[38;5;226m[HOST]\e[0m"
         rm /tmp/install > /dev/null 2>&1
         ;;

       4)
         clear
         rm /tmp/install > /dev/null 2>&1
         SALIR=1
         ;;

       *)
         clear
         echo "Opcion erronea";;
   esac
done
