#!/bin/sh

clear

SALIR=0
OPCION=0
while [ $SALIR -eq 0 ]; do
echo -e "\e[1;40;32m####################################################################\e[0m"
echo -e "\e[1;40;32m#								   #\e[0m"
echo -e "\e[1;40;32m# SCRIPT PUBLICADO POR perraka DE MULTICS.ES Y MODIFICADO POR PIFO #\e[0m"
echo -e "\e[1;40;32m# FOROS AUTORIZADOS PARA PUBLICACION                               #\e[0m"
echo -e "\e[1;40;32m# MULTICSFORO.COM                                                  #\e[0m"
echo -e "\e[1;40;32m# MULTICS.EU                                                       #\e[0m"
echo -e "\e[1;40;32m# MULTICS.ES                                                       #\e[0m"
echo -e "\e[1;40;32m#								   #\e[0m"
echo -e "\e[1;40;32m#			ULTIMA EDICION 27-05-2021		   #\e[0m"
echo -e "\e[1;40;32m#								   #\e[0m"
echo -e "\e[1;40;32m####################################################################\e[0m"
echo -e "\e[38;5;75mMenu:\e[0m"

   echo -e "\e[1;40;37m1) \e[1;40;32mInstalar Firewall\e[0m"
   echo -e "\e[1;40;37m2) \e[1;40;31mEliminar Firewall\e[0m"
   echo -e "\e[1;40;37m3) \e[38;5;75mManual de Uso Para Ban/Unban\e[0m"
   echo -e "\e[1;40;376m4) \e[38;5;226mSalir\e[0m"
   echo -e "\e[38;5;75mOpcion seleccionada:\e[0m"
   read OPCION
   case $OPCION in
       1)
clear
apt-get install dnsutils curl -y > /dev/null 2>&1
mkdir /etc/myOwnFirewall > /dev/null 2>&1
wget https://pifo-emu.github.io/Firewall-multics/Firewall -O /etc/myOwnFirewall/myOwnFirewall > /dev/null 2>&1
chmod +x -R /etc/myOwnFirewall

SALIR2=0
red0=0

red1=$(ip a | grep $(curl -s -4 ifconfig.me) | cut -f11-12 -d ' ')
echo "SE A DETECTADO $red1 COMO NOMBRE DE TARJETA DE RED"
echo -e "\e[1;40;35m$red1 ES EL NOMBRE CORRECTO DE TU TARJETA DE RED?\e[0m" 

   echo -e "\e[1;40;37m1) \e[1;40;32mSI\e[0m"
   echo -e "\e[1;40;37m2) \e[1;40;31mNO\e[0m"

read red0
   case $red0 in
       1) echo OK
sed s/"red_"/"$red1"/g -i /etc/myOwnFirewall/myOwnFirewall 

           SALIR2=1 ;;

       2) echo -e "\e[1;40;35mDIME EL NOMBRE DE TU TARJETA DE RED\e[0m" 
read red_
sed s/"red_"/"$red_"/g -i /etc/myOwnFirewall/myOwnFirewall 

           SALIR2=1 ;;
esac

echo -e "\e[1;40;35mPUERTOS QUE USA LA MULTICS EN LOS PROFILES. E.j: 8000:8010\e[0m"
read pro_
sed s/"pro_"/"$pro_"/g -i /etc/myOwnFirewall/myOwnFirewall 

echo -e "\e[1;40;35mPUERTO HTTP QUE USA LA MULTICS. E.j: 8888\e[0m"
read web_
sed s/"web_"/"$web_"/g -i /etc/myOwnFirewall/myOwnFirewall 

echo -e "\e[1;40;35mPUERTOS QUE USA LA MULTICS PARA CCCAM MGCAMD O CUALQUIER OTRO PROTOCOLO QUE USES. E.j: 4000,12001,18003,...\e[0m"
read pr2_
sed s/"pr2_"/"$pr2_"/g -i /etc/myOwnFirewall/myOwnFirewall 

echo -e "\e[1;40;35mPUERTOS QUE USA LA MULTICS PARA CACHE SI TIENES MAS DE UNA CACHE EN ESTE SERVIDOR SEPARA LOS PUERTOS CON "," COMAS. E.j: 5000,5001\e[0m"
read cac_
sed s/"cac_"/"$cac_"/g -i /etc/myOwnFirewall/myOwnFirewall 

SALIR3=0
SSH3=0

SSH1=$(netstat -putona | grep sshd | grep LISTEN | grep 0.0.0.0: |  cut -f2 -d ':' | cut -f1 -d ' ')
echo "SE A DETECTADO $SSH1 COMO PUERTO SSH"
echo -e "\e[1;40;35m$SSH1 ES EL PUERTO CORRECTO DE SSH?\e[0m" 

   echo -e "\e[1;40;37m1) \e[1;40;32mSI\e[0m"
   echo -e "\e[1;40;37m2) \e[1;40;31mNO\e[0m"

read SSH3
   case $SSH3 in
       1) echo OK
sed s/"ss_"/"$SSH1"/g -i /etc/myOwnFirewall/myOwnFirewall 

           SALIR3=1 ;;

       2) echo -e "\e[1;40;35mDIME TU PUERTO SSH\e[0m"
echo -e "\e[1;40;31m!!ATENCION!! NO TE EQUIVOQUES\e[0m"
read ss_
sed s/"ss_"/"$ss_"/g -i /etc/myOwnFirewall/myOwnFirewall 

           SALIR3=1 ;;
esac



ln -s /etc/myOwnFirewall/myOwnFirewall /usr/sbin/f > /dev/null 2>&1
ln -s /etc/myOwnFirewall/myOwnFirewall  /etc/init.d/myOwnFirewall > /dev/null 2>&1

touch /etc/myOwnFirewall/banList > /dev/null 2>&1

SALIR4=0
OK2=0

echo -e "\e[1;40;31m!!ATENCION!! AHORA REALIZAREMOS UN TEST TENDRAS 1 MINUTO PARA REALIZAR LAS PRUEBAS\e[0m"
echo -e "\e[1;40;31mPRUEBA QUE TENGAS ACCESO A LA MULTICS Y A SSH\e[0m"

/etc/myOwnFirewall/myOwnFirewall test

echo -e "\e[1;40;31m!!ATENCION!! TUVISTES ACCESO A SSH Y A LA MULTICS?\e[0m"
   echo -e "\e[1;40;37m1) \e[1;40;32mSI\e[0m"
   echo -e "\e[1;40;37m2) \e[1;40;31mNO\e[0m"

read OK2
   case $OK2 in
       1) echo OK
systemctl enable myOwnFirewall > /dev/null 2>&1
/etc/myOwnFirewall/myOwnFirewall start

           SALIR4=1 ;;

       2) 
echo "VUELVE A INTENTARLO EN OTRO MOMENTO HOY NO ES TU DIA"
echo "O SOLICITA AYUDA EN EL FORO"
echo "AHORA ELIMINARE LO QUE YA SE HABIA INSTALADO PARA QUE EMPIECES NUEVAMENTE "
rm -rf  /etc/myOwnFirewall /usr/sbin/f /etc/init.d/myOwnFirewall > /dev/null 2>&1
           SALIR4=1 ;;

esac
;;
       2)
clear
/etc/myOwnFirewall/myOwnFirewall stop  > /dev/null 2>&1
rm -rf  /etc/myOwnFirewall /usr/sbin/f /etc/init.d/myOwnFirewall > /dev/null 2>&1
           rm /tmp/install > /dev/null 2>&1

echo -e "\e[1;40;31mFirewall Eliminado\e[0m"

           SALIR=1 ;;

       3)
           clear
   echo -e "\e[1;40;32mBan IP: /etc/myOwnFirewall/myOwnFirewall ban \e[38;5;226m[IP]\e[0m"
   echo -e "\e[1;40;32mBan IP: /etc/myOwnFirewall/myOwnFirewall ban \e[38;5;226m[HOST]\e[0m"
   echo -e "\e[1;40;32mUnban IP: /etc/myOwnFirewall/myOwnFirewall unban \e[38;5;226m[IP]\e[0m"
   echo -e "\e[1;40;32mUnban IP: /etc/myOwnFirewall/myOwnFirewall unban \e[38;5;226m[HOST]\e[0m"
              rm /tmp/install > /dev/null 2>&1

           SALIR=1 ;;

       4)
           clear
           rm /tmp/install > /dev/null 2>&1
           SALIR=1 ;;
       *)
           clear
         echo "Opcion erronea";;
   esac
done
